### ISSUE TITLE
[Module]: Language Packs

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks.nvim#242]
NOTE: The goal of this issue is not to supercede lspconfig nor mason.

We've already done a good job making tree-sitter parsers easier to use (just a few things need fleshing out).

A `rocks-ide.nvim`/`rocks-languages.nvim`/`rocks-language-packs.nvim` package would be nuts. We could bundle a set of language packs (with LSP setup, DAP setup) for most common languages in some deterministic way. We could even go as far as setting up completion engines (doable thanks to proper dependency support) as well as snippet engines of the user's choice (yet again doable thanks to proper dependency support).

Language packs could all be hosted in one monorepo or as separate rocks (`rocks-lua-language-pack.nvim`).

Example configuration:
```toml

[engines]
completions = "nvim-cmp" # Automatically set up nvim-cmp
snippets = "luasnip" # Automatically set up luasnip with nvim-cmp

[languages]
lua = {} # Enable the lua language pack with default options

# Enable the cpp language pack with custom settings
[languages.cpp]
lsp = {
    # lsp settings go here
}
dap = {
    #  dap settings go here
}

# etc...
```

To make things adequately extensible, one should be able to interact with these from Lua too for dynamic option switching. We shouldn't lock users in this much extensibility wise.

Happy to hear thoughts on this too.
