### ISSUE TITLE
sync: do not attempt to remove dependencies

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#3]
## Summary

If a plugin that other plugins depend on is removed from rocks.toml,
rocks.nvim attempts to remove it.

## Spec

Given the following rocks.toml:

```toml
[plugins]
"haskell-tools.nvim" = "2.3.0" # depends on plenary.nvim
"plenary.nvim" = "0.1.3"
```
And both plugins have been installed with `:Rocks install`
When I remove plenary.nvim from the rocks.toml as follows:
```toml
[plugins]
"haskell-tools.nvim" = "2.3.0" # depends on plenary.nvim
```
And I execute `:Rocks sync`

### Expected behaviour
Then nothing happens

### Current behaviour
Then the rocks.nvim displays "Removing 'plenary.nvim'"

## Implementation details

- `luarocks` does not have a way to list dependencies, but `luarocks show <rock_name>` will list the dependencies of each rock.
- We could use this on each rock in `rocks.toml` to gather all dependencies, and then filter the list of rocks to remove accordingly.
