### ISSUE TITLE
E5113: attempt to index field 'rocks' (a nil value)

### ISSUE THREAD

**Issue by craigmac** [nvim-neorocks/rocks.nvim#417]
Using this rocks.toml file:

```toml
[plugins]
"rocks.nvim" = "2.32.0"
"rocks-git.nvim" = "1.5.1"
"rocks-config.nvim" = "2.1.0"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

nvim-treesitter-context = "scm"
nvim-treesitter-textobjects = "scm"

[bundles.treesitter]
items = [
  "nvim-treesitter",
  "nvim-treesitter-context",
  "nvim-treesitter-textobjects"
]
```

Error, upon `nvim` start:

```
Error detected while processing /Users/craigmaceachern/.local/share/nvi
m/rocks/lib/luarocks/rocks-5.1/rocks.nvim/2.32.0-1/plugin/rocks.lua:
E5113: Error while calling lua chunk: ...share/nvim/rocks/rocks_rtp/lua
/rocks-config/internal.lua:221: attempt to index field 'rocks' (a nil v
alue)
stack traceback:
        ...share/nvim/rocks/rocks_rtp/lua/rocks-config/internal.lua:221
: in function 'f'
        /usr/local/share/nvim/runtime/lua/vim/iter.lua:625: in function
 'fn'
        /usr/local/share/nvim/runtime/lua/vim/iter.lua:633: in function
 'find'
        ...share/nvim/rocks/rocks_rtp/lua/rocks-config/internal.lua:220
: in function 'setup'
        ...rocks/rocks_rtp/lua/rocks-config/rocks/hooks/preload.lua:18:
 in function 'action'
        ...local/share/nvim/rocks/rocks_rtp/lua/rocks/api/hooks.lua:93:
 in function 'run_preload_hooks'
        .../luarocks/rocks-5.1/rocks.nvim/2.32.0-1/plugin/rocks.lua:61:
 in main chunk
```
