### ISSUE TITLE
macOS: Luarocks installs parsers for the wrong architecture

### ISSUE THREAD

**Issue by bottd** [nvim-neorocks/rocks.nvim#458]
This was originally working for me, but I have had no luck troubleshooting in the past couple of days. I get the following error in `:checkhealth` for any parser installed using `rocks.nvim`:

```
- ERROR Parser "toml" failed to load (path: /Users/drakebott/.local/share/nvim/site/pack/luarocks/opt/tree-sitter-toml/parser/toml.so): ....10.0/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'toml': uv_dlopen: no error
- ERROR Parser "toml.so" failed to load (path: /Users/drakebott/.local/share/nvim/site/pack/luarocks/opt/tree-sitter-toml/parser/toml.so.dSYM): ....10.0/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'toml.so' is not a valid language name
```

For a minimal reproduction on my machine I removed and reinstalled a clean Neovim 0.10.0, placed the rocks bootstrap script in `init.lua` and used the following `rocks.toml`:

```toml
[plugins]
"rocks.nvim" = "2.33.0" # rocks.nvim can also manage itself :D
"rocks-treesitter.nvim" = "scm"
tree-sitter-toml = "scm"
```
