### ISSUE TITLE
`:Rocks sync` fails on first install when `rocks.toml` has plugins that require `rocks-git`

### ISSUE THREAD

**Issue by craigmac** [nvim-neorocks/rocks.nvim#607]
Seems to be an out-or-order sort of bug. If I clone my nvim repo on new box, when I try doing a `:Rocks sync` I get messages about failures for the rocks that are dependent on rock-git being installed. Is there a way to prioritize `rocks-git.nvim` being installed and loaded first if it exists in the `rocks.toml` file?

Currently, the way to workaround this is just to close and open neovim and run `:Rocks sync` again, which will now work because `rocks-git.nvim` would have been installed the first time we ran `:Rocks sync`.

Alternatively, maybe there should be `config = "rocks-git.toml"` setting like was introduced for the `rocks-treesitter.nvim` plugin?

**Comment by craigmac** [comment]
example `rocks.toml`:

```toml
[rocks]

[plugins]
"rocks.nvim" = "2.42.1"
"rocks-git.nvim" = "2.5.2"
"gitsigns.nvim" = "0.9.0"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "v3.7"
```
