### ISSUE TITLE
[Module]: `rocks-config` for common configuration paradigms

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks.nvim#72]
The default (expected) way to handle plugins within one's configuration is to place plugins in a `plugins/` RTP directory and check for the existence of the plugin with `pcall`.

A `rocks-config` module would allow users to specify per-plugin configuration files (if the plugin is installed and loaded). A global option could also be set which would specify the default directory where files for plugins would be sourced, e.g.:
```toml
[plugins]
# plugins go here...

[config]
path = "plugins/" # search in `$CONFIG_DIR/lua/plugins/xyz.lua` for each installed plugin
```
