### ISSUE TITLE
[Module]: `rocks-git` for pulling plugins that don't exist on luarocks

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks.nvim#81]
Not everyone must have their plugins present on luarocks. This module would allow users to specify a `git` repository for installation of their plugins:
```toml
[plugins.neorg]
git = "nvim-neorg/neorg"

# or...

[plugins]
neorg = { git = "nvim-neorg/neorg", version = "1.0.0" }
```
