### ISSUE TITLE
[Module] `rocks-lazy` module for lazy-loading plugins

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#87]
Depends on #86.

Users could add things like events or filetypes to their plugin config, to load plugins lazily.

```toml
[plugins]
rustaceanvim = { version = "1.0.0", opt = true, filetypes = [ "rust" ] }
```
