### ISSUE TITLE
[Module]: `rocks-dev` for installation of local plugins

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks.nvim#94]
I was considering adding this feature as part of `rocks.nvim` core, but now that I have considered it I feel like it would make more sense to have as an external module.

This module would allow developers to test local, development versions of their plugin without having to push their code to a `dev` target on `luarocks.org`.

Idea for syntax:
```toml
[plugins.neorg]
dir = "~/dev/neorg/"

# or ...

[plugins]
neorg = { dir = "~/dev/neorg" }
```

When specified like this the `version` parameter would simply be ignored. `:Rocks sync` would not affect these entries. Any plugin that is specified with `dir` would simply be manually added by `rocks-dev` to the runtimepath.
