### ISSUE TITLE
[BUG]: `:Rocks update` does not respect TOML structure

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks.nvim#96]
## Current Behaviour

Consider the following rocks.toml:

```toml
[plugins]
"sweetie.nvim" = { version = "xxx" }
```

Upon running `:Rocks update`, `rocks.nvim` will forcefully coerce the table down to the following:
```toml
[plugins]
"sweetie.nvim" = "xxx"
```

## Expected Behaviour

`rocks.nvim` should only do this coercion if the type of the plugin is not a `table`.
